version: "3.7"

services:

  quarkus-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: "mdas/quarkus-build:${BUILD_VERSION}"
    container_name: quarkus-build
    networks:
      - quarkus-network
    volumes:
      - ./:/app
#      - ./.mvn/m2_repository:/home/dev/.m2/repository
    working_dir: /app
    env_file:
      - .env

  quarkus-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: "mdas/quarkus-app:${APP_VERSION}"
    container_name: quarkus-app
    networks:
      - quarkus-network
    env_file:
      - .env
#    ports:
#      - 80:8080

#Docker Networks
networks:
  quarkus-network:
    driver: bridge

